--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--Q2. Show revenue by category (highest first)
select category, SUM(purchase_amount) as revenue
from customer
group by category
order by revenue desc
--Q3. Find second highest purchase amount
select distinct purchase_amount 
from customer
order by purchase_amount desc
offset 1 limit 1
--Q4.Who are the top 5 customers by spending?
select  distinct customer_id, SUM(purchase_amount)as total_spent
from customer
group by customer_id
order by total_spent desc
limit 5
--Q5.Which category has the most orders?
select category, COUNT(*) as total_orders
from customer
group by category
order by total_orders desc
limit 1
--Q6.Which payment method is used most?
select payment_method, COUNT(*) as most_usage
from customer
group by payment_method
order by most_usage desc
limit 1
--Q7.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
COUNT (distinct customer_id)as repeat_buyer
from customer
where previous_purchases > 5
group by subscription_status
--Q8.Find customers who spent more than average
select customer_id
from customer
where purchase_amount > (
select  AVG(purchase_amount) from customer)
--Q9.Categorize customers into High, Medium, Low spenders
select customer_id,SUM(purchase_amount) as total_spent,
CASE
when SUM(purchase_amount) >= 1000 then 'High'
when SUM(purchase_amount) >= 500 then 'Medium'
else 'Low'
end as segment
from customer
group by customer_id
--Q10.Calculate running total of sales
select purchase_amount,
SUM(purchase_amount) over() as total_sales
from customer
group by purchase_amount
--Q11.What is the revenue contribution of each age group? 
select age_group, SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc


